name : First_workflow

on:
  pull_request:
    branches:
      - br1

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: print("hello world")
        shell: python
  second:
    runs-on: windows-latest
    steps:
      - name: bye
        run: print("end")
        shell: python


